config/routes.rb
Rails.application.routes.draw do
  root 'wallets#index'
  resources :txes, only: [:index, :show]
  resources :blocks, only: [:index, :show]
  resources :wallets, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/block.rb
class Block < ApplicationRecord
  paginates_per 50
  has_and_belongs_to_many :txes
end

app/models/tx.rb
class Tx < ApplicationRecord
  paginates_per 50
  has_and_belongs_to_many :blocks
  has_many :tx_ins
  has_many :tx_outs

  def to_param
    tx_hash
  end

  def to_hash
    h = {
      hash: tx_hash,
      ver: ver,
      vin_sz: vin_sz,
      vout_sz: vout_sz,
      lock_time: lock_time,
      size: size
    }

    h[:in] = tx_ins.map do |tx_in|
      tx_in_h = {
        prev_out: {
          hash: tx_in.prevout_hash,
          n: tx_in.n
        },
        scriptSig: tx_in.script_sig,
      }
      tx_in_h[:sequence] = tx_in.sequence if tx_in.sequence.present?
      tx_in_h
    end

    h[:out] = tx_outs.map do |tx_out|
      {
        value: tx_out.btc_value,
        scriptPubKey: tx_out.script_pubkey,
      }
    end

    HashWithIndifferentAccess.new(h)
  end
end

app/models/tx_in.rb
class TxIn < ApplicationRecord
  belongs_to :tx
end

app/models/tx_out.rb
class TxOut < ApplicationRecord
  belongs_to :tx

  def address_type
    return 'NONE' unless address.present?
    case address
      when /^1/
        'P2PKH'
      when /^3/
        'P2SH'
      when /^bc1/
        'Bech32'
      else
        'UNKNOWN'
    end
  end

  def btc_value
    sprintf "%.8f", (value.to_f / 10**8)
  end
end

app/models/wallet.rb
class Wallet < ApplicationRecord
  paginates_per 50
  def balance
    query = <<-SQL.strip_heredoc
    select 
      sum(tx_outs.value)
    from tx_outs
    left join (
      select
        tx_outs.id
      from tx_ins
      join txes on txes.tx_hash = tx_ins.prevout_hash
      join blocks_txes on blocks_txes.tx_id = txes.id
      join tx_outs on tx_outs.id = (
          select id from tx_outs
          where tx_outs.tx_id = txes.id
          order by created_at desc
          offset tx_ins.n limit 1
      )
    ) as spent_tx_outs on spent_tx_outs.id = tx_outs.id
    where tx_outs.address = '#{address}'      
    and spent_tx_outs.id is null
    SQL
    ActiveRecord::Base.connection.execute(query).to_a.first['sum']
  end

  def txes
    Tx.joins(:tx_outs).where('tx_outs.address = ?', address)
  end

  def balance_btc
    sprintf "%.8f", (balance.to_f / 10**8)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blocks_controller.rb
class BlocksController < ApplicationController
  def index
    @blocks = Block.page(params[:page])
  end

  def show
    @block = Block.find(params[:id])
  end
end

app/controllers/txes_controller.rb
class TxesController < ApplicationController
  def index
    @txes = Tx.page(params[:page])
  end

  def show
    @tx = Tx.find_by(tx_hash: params[:id])
  end
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
  def index
    @wallets = Wallet.page(params[:page])
  end

  def show
    @wallet = Wallet.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/block_txes_helper.rb
module BlockTxesHelper
end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/helpers/txes_helper.rb
module TxesHelper
end

app/helpers/txins_helper.rb
module TxinsHelper
end

app/helpers/txouts_helper.rb
module TxoutsHelper
end

app/views/blocks/index.html.slim
p#notice
  = notice
h1
  | Blocks
table.table.table-striped.table-responsive
  thead
    tr
      th block_hash
      th ver
      th prev_block
      th mrkl_root
      th time
      th bits
      th nonce
      th n_tx
      th size
  tbody
    - @blocks.each do |block|
      tr
        td= link_to block.block_hash, block
        td= block.ver
        td= block.prev_block
        td= block.mrkl_root
        td= block.time
        td= block.bits
        td= block.nonce
        td= block.n_tx
        td= block.size

app/views/blocks/show.html.slim
= link_to 'Back', blocks_path

table
  tr
    td Hash:
    td= @block.block_hash
  tr
    td Version:
    td= @block.ver
  tr
    td Prev Block
    td= @block.prev_block
  tr
    td mrkl_root
    td= @block.mrkl_root
  tr
    td Time
    td= @block.time
  tr
    td Bits
    td= @block.bits
  tr
    td Nonce
    td= @block.nonce
  tr
    td N Tx
    td= @block.n_tx
  tr
    td Size
    td= @block.size

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8" /
    meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport" /
    meta content="" name="description" /
    meta content="" name="author" /
    link href="../../../../favicon.ico" rel="icon" /
    title Bitcoin Monitor
    = stylesheet_pack_tag 'application'
    = javascript_pack_tag 'application'
  body
    nav.navbar.navbar-expand-md.navbar-dark.bg-dark.fixed-top
      a.navbar-brand href="#"  Bitcoin Monitor
      button.navbar-toggler aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarsExampleDefault" data-toggle="collapse" type="button"
        span.navbar-toggler-icon
      #navbarsExampleDefault.collapse.navbar-collapse
        ul.navbar-nav.mr-auto
          li.nav-item.active
            a.nav-link href="#"
              | Home
              span.sr-only (current)
          li.nav-item
            = link_to 'Wallets', wallets_path, class: 'nav-link'
          li.nav-item
            = link_to 'Transactions', txes_path, class: 'nav-link'
          li.nav-item
            = link_to 'Blocks', blocks_path, class: 'nav-link'

    = yield

app/views/txes/_tx.html.slim
tr
  td= link_to tx.tx_hash, tx
  td
    - tx.tx_ins.each do |tx_in|
      p
        - if tx_in.coinbase.present?
          | COINBASE
        - else
          = tx_in.prevout_hash
  td
    - tx.tx_outs.each do |tx_out|
      p
        small= "(#{tx_out.address_type})"
        = tx_out.address
        | ->
        = tx_out.value.to_f / 10**8
        | BTC

  td= tx.size
  td= tx.created_at

app/views/txes/index.html.slim
h1
  | Transactions
table.table.table-striped.table-responsive
  thead
    tr
      th Hash
      th Inputs
      th Outputs
      th Size
      th Created At

  tbody
    = render @txes

= paginate @txes

app/views/txes/show.html.slim
= link_to 'Back', txes_path

- if @tx.blocks.exists?

.panel
  table
    tr
      td Hash:
      td= @tx.tx_hash
    tr
      td Ins:
      td= @tx.tx_ins.count
    tr
      td Outs:
      td= @tx.tx_outs.count
    tr
      td Size:
      td= @tx.size
    tr
      td Created at:
      td= @tx.created_at

.panel
  = @tx.as_json.to_json

app/views/wallets/index.html.slim
h1
  | Wallets
table.table.table-striped.table-responsive
  thead
    tr
      th Address
      th Balance
      th Created At

  tbody
    - @wallets.each do |wallet|
      tr
        td= link_to wallet.address, wallet
        td= wallet.balance_btc
        td= wallet.created_at

= paginate @wallets

app/views/wallets/show.html.slim
= link_to 'Back', wallets_path

table
  tr
    td Address:
    td= @wallet.address
  tr
    td Balance:
    td= @wallet.balance_btc
  tr
    td Created at:
    td= @wallet.created_at

h1 Transactions
table.table.table-striped.table-responsive
  thead
    tr
      th Hash
      th Inputs
      th Outputs
      th Size
      th Created At
  tbody
    = render @wallet.txes